### ISSUE TITLE
Thread 1: signal SIGABRT

### ISSUE THREAD

**Issue by shinbc** [holepunchto/bare-kit#10]
I tried to implement this framework into swift project.
But when I call start function, I'm getting crash.
Could you help me?

**Comment by kasperisager** [comment]
The Bare thread will abort on uncaught exceptions by default so check the logs for more information. If there's nothing there, post your code and I'd be happy to take a look.

**Comment by kasperisager** [comment]
See https://github.com/holepunchto/bare-ios/blob/main/app/App.swift for a reference on how to call Bare Kit from Swift.
