### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by warmachinesocial** [holepunchto/bare-kit#4]
Would like to have more demo examples on how to make use of it? Plus more documentation on how to integrate bare-kit on different platforms.

**Comment by kasperisager** [comment]
Bare Kit is currently focused on mobile usage, with fairly complete usage examples provided by https://github.com/holepunchto/bare-ios and https://github.com/holepunchto/bare-android. Do keep in mind that the API still isn't finalised, so things are likely to change.
