### ISSUE TITLE
Question on Framework 

### ISSUE THREAD

**Issue by warmachinesocial** [holepunchto/bare-kit#5]
To  be honest, I don't know much on Cmake or framework in ios however I recently played with static library and how to integrate in swift. Was wondering if this dynamic or static lib or how does framework wrap this? Just wanna learn on that side. 

How easily would it be to use the barekit framework?

**Comment by kasperisager** [comment]
The resulting `BareKit.framework` wraps a dynamic library. You can then compile several of these for the various SDKs and architectures, all of which are produced by the prebuild workflow (https://github.com/holepunchto/bare-kit/actions/workflows/prebuild.yml), into a universal `BareKit.xcframework`. That's precisely what we ship in `react-native-bare-kit`: https://unpkg.com/browse/react-native-bare-kit@latest/ios/BareKit.xcframework/

**Comment by kasperisager** [comment]
We now ship `.xcframework` prebuilds as part of the releases: https://github.com/holepunchto/bare-kit/releases/tag/v1.0.0
